#!/bin/bash

TELEGRAM_BOT_TOKEN="YOUR_TELEGRAM_BOT_TOKEN"
XAMPP_INSTALLER_URL="https://www.apachefriends.org/xampp-files/XAMPP-VERSION-x86_64-installer.run" # Replace VERSION with the desired XAMPP version

cloudflared_start() {
   cloudflared tunnel run --config cloudflared-config.yaml
}

start_xampp() {
   /opt/lampp/lampp start
}

stop_xampp() {
   /opt/lampp/lampp stop
}

install_xampp() {
   send_telegram_message "$chat_id" "Downloading and installing XAMPP..."
   wget "$XAMPP_INSTALLER_URL" -O xampp-installer.run
   chmod +x xampp-installer.run
   sudo ./xampp-installer.run
   rm xampp-installer.run
   send_telegram_message "$chat_id" "XAMPP installation completed. You can now start XAMPP with /startxampp."
}

handle_telegram_command() {
   local chat_id="$1"
   local command="$2"

   case "$command" in
       "/start")
           send_telegram_message "$chat_id" "Welcome to your Cloudflared and XAMPP control! You can start XAMPP with /startxampp, stop XAMPP with /stopxampp, start Cloudflared with /startserver, and stop Cloudflared with /stopserver. You can also install XAMPP with /installxampp."
           ;;
       "/startserver")
           send_telegram_message "$chat_id" "Starting the Cloudflared server..."
           cloudflared_start
           ;;
       "/startxampp")
           send_telegram_message "$chat_id" "Starting XAMPP..."
           start_xampp
           ;;
       "/stopserver")
           send_telegram_message "$chat_id" "Stopping the Cloudflared server..."
           ;;
       "/stopxampp")
           send_telegram_message "$chat_id" "Stopping XAMPP..."
           stop_xampp
           ;;
       "/installxampp")
           install_xampp
           ;;
       *)
           send_telegram_message "$chat_id" "Unknown command: $command"
           ;;
   esac
}

send_telegram_message() {
   local chat_id="$1"
   local message="$2"

   curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" \
       -d "chat_id=$chat_id" \
       -d "text=$message"
}

main() {
   while true; do
       update=$(curl -s "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/getUpdates?offset=-1")
       chat_id=$(echo "$update" | jq -r '.result[0].message.chat.id')
       message_text=$(echo "$update" | jq -r '.result[0].message.text')
       handle_telegram_command "$chat_id" "$message_text"
   done
}

main
